font:
  size:
    heading_huge: 17pt
    heading_large: 14pt
    heading: 11pt
    description: 8pt
    tags: 8pt
    education_description: 8pt
    contacts: 8pt
  general: "Helvetica Neue"
  minor_highlight: "Helvetica Neue"

paragraph:
  # Distance between lines
  leading: 4pt
