- name: Add config on port 443
  template:
    src: templates/config_domain_443.j2
    dest: /etc/nginx/sites-enabled/{{ domain.name }}_443
  notify:
    - Reload nginx
- name: Update new_sites_enabled_paths
  set_fact:
    new_sites_enabled_paths: "{{ new_sites_enabled_paths | default([]) + ['/etc/nginx/sites-enabled/' + domain.name + '_443'] }}"
