- name: Install nginx and letsencrypt
  apt:
    name: [ 'nginx', 'letsencrypt' ]
    state: present

- name: Configure letsencrypt
  include_tasks: configure_letsencrypt.yml
  loop: "{{ domains | selectattr('enforce_https', 'equalto', true) }}"
  loop_control:
    loop_var: domain

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem
- name: Install system nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Reload nginx

- name: Remember sites-enabled paths
  set_fact:
    new_sites_enabled_paths: []
- name: Configure enabled sites on port 80
  include_tasks: configure_domain_80.yml
  loop: "{{ domains | selectattr('enforce_https', 'equalto', true) }}"
  loop_control:
    loop_var: domain
- name: Configure enabled sites on port 443
  include_tasks: configure_domain_443.yml
  loop: "{{ domains }}"
  loop_control:
    loop_var: domain
- name: Drop obsolete sites
  include_tasks: drop_obsolete_sites.yml

- name: Add cronjob for reloading nginx daily
  cron:
    name: reload_nginx
    special_time: daily
    job: systemctl reload nginx
